# FROM mcr.microsoft.com/devcontainers/javascript-node
FROM nodejs/devcontainer
# FROM mcr.microsoft.com/devcontainers/typescript-node:20


# Install the lf package
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y lf fd lazygit