# FROM mcr.microsoft.com/devcontainers/javascript-node
# FROM nodejs/devcontainer:nightly
FROM mcr.microsoft.com/devcontainers/typescript-node


# Install the lf package
RUN apt-get update && apt-get install -y lf