<script>
</script>

<div class="min-h-screen grid place-items-center">
  <div
    class="flex justify-center items-center text-center birthday text-7xl leading-[1.2em] swirl-in-fwd"
  >
    Happy Birthday
  </div>
</div>

<style>
  @import url('https://fonts.googleapis.com/css2?family=Nabla&display=swap');
  .birthday {
    font-family: 'Nabla', sans-serif;
  }
  :global(body) {
    background: repeating-conic-gradient(
        hsla(198.13, 81.36%, 23.14%, 1) 0deg 15deg,
        hsla(203.73, 57.26%, 45.88%, 1) 0deg 30deg,
        hsl(0deg 0% 80% / 31%) 0deg 15deg,
        hsla(0, 0%, 100%, 0) 0deg 30deg
      )
      #3c1c32;
  }

  .swirl-in-fwd {
    animation: swirl-in-fwd 1s ease-out both;
    animation-delay: 2s;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2024-1-16 21:58:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation swirl-in-fwd
 * ----------------------------------------
 */
  @keyframes swirl-in-fwd {
    0% {
      transform: rotate(-960deg) scale(0);
      opacity: 0;
    }
    100% {
      transform: rotate(0) scale(1);
      opacity: 1;
    }
  }
</style>
